### ISSUE TITLE
Add support for default logging properties

### ISSUE THREAD

**Issue by regadas** [spotify/flyte-flink-plugin#26]

**Comment by syodage** [comment]
As I understood, how this should work is; users pass the custom logging properties via task context and we set these custom logging properties on FlinkClusterSpec of Kubernetes operator. 

we need to do the following to get this working, 
- Update the [config.go](https://github.com/spotify/flyte-flink-plugin/blob/master/pkg/flink/config.go#L47) to add this new property.
- extract these custom logging properties [here](https://github.com/spotify/flyte-flink-plugin/blob/master/pkg/flink/handler.go#L87) and pass it to `BuildFlinkClusterSpec`
- In the [resource.go](https://github.com/spotify/flyte-flink-plugin/blob/master/pkg/flink/resources.go#L251), set this to [FlinkClusterSpec](https://github.com/spotify/flyte-flink-plugin/blob/master/pkg/flink/resources.go#L261) object. 
- Above step requires to tweak the `FlinkClusterSpec` in the flink operator to hold the value.

Before doing this I would like to know the rationale behind this change. At which point and/or where we will use these properties?
